### ISSUE TITLE
Some questions about your example

### ISSUE THREAD

**Issue by corsariovasco** [RasaHQ/pizza-rule-demo#1]
Hi!
I am rookie with this technology and I have test your code. I have some questions.
According to: 
a) on the domain.yml file I think that only action_flush_slots is necessary in action section.
b) on the stories.yml file. I think that only the happy path story, the sad path 1story and the sad path 2 story are necessary. The rest migth be rules.
c) What is the meaning the conversation_start: true? is used to  init the conversation by the bot?. The greet also migth be a rule.
d) In actions.py file better change the order "for key in ("topping", "size")" to for key in ("size", "topping"). As the order of the questions that done the bot. And better change the name of the Class to ActionFlushSlots.

What is your opinion?.

Kindly regards,

**Comment by koaning** [comment]
Hi. 

This repo should be considered "work in progress". That's why the readme file doesn't contain any ways to get started. 

That said; I can answer a few questions. 

a. True, but the other actions are automatically filled by using `rasa interactive`. 
b. These stories were also added by `rasa interactive`. The goal on my end here was to also have story examples with the form such that I have a template where I can insert chit-chat. 
c. This is something you can add to a rule to make it more specific. The rule will only be triggered at the start of a conversation. 
d. Since the action will flush *all* slots, does the order really matter? The action classname can be better though, I can certainly agree with that.

**Comment by corsariovasco** [comment]
Hi,
Sorry I didn't know that it is a "work in progress". But I would like to say that is good work (It has helped me). An example simple to a beginner. Your code is current and there are not much examples like this.

Thanks for your explanation.

Kind regards,

**Comment by koaning** [comment]
This is actually a good "datapoint" for me. I haven't gotten any tutorials that start from scratch using Rasa 2.0. 

I might make a knock-knock joke assistant next week. It's something that I've wanted to make for a while and I'd be nice to have a tutorial that's made from scratch using Rasa 2.0.

**Comment by corsariovasco** [comment]
In order to do this,  if you share it, i will test your project.
Come on!  with a good idea.
Thanks in advance.
Kind regards

P.D.: When I have more mature this technology if you need me to help you, tell me, please.
